[[redirects]]
  from = "/"
  to = "https://datacartographer.com/covid"
  status = 301
  force = true

[[redirects]]
  from = "/#/"
  to = "https://datacartographer.com/covid"
  status = 301
  force = true